apiVersion: kro.run/v1alpha1
kind: MessageProcessor
metadata:
  name: orders
spec:
  name: orders
  environment: dev
  replicas: 1
  messageRetentionPeriod: "86400"
  image: k3d-cloud-registry:5000/orders-processor:v1.0.0
